### ISSUE TITLE
Do we need these VIs?

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#12]
![image](https://user-images.githubusercontent.com/26659428/84943353-3fd7dc80-b0b2-11ea-814a-7a98aa66e9b9.png)

They have no callers

**Comment by Monkeymerlot** [comment]
Neither of them have anything on their connector panes:
![image](https://user-images.githubusercontent.com/37567672/84971991-eee4da00-b0eb-11ea-9c53-75c7af89cd99.png)
![image](https://user-images.githubusercontent.com/37567672/84972010-f7d5ab80-b0eb-11ea-923e-df491b4b98ba.png)
To be honest they look like someone created them when they were debugging and forgot to delete them. I will see if I can still run the code without them

**Comment by Monkeymerlot** [comment]
It seemed to work fine without them so I removed them.
