### ISSUE TITLE
Bevier.vi vs Bezier Curve.vi?

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#13]
![image](https://user-images.githubusercontent.com/26659428/85067280-6b27fd80-b17e-11ea-8148-ab9d1a99d80f.png)

**Comment by Monkeymerlot** [comment]
I think I added a bookmark talking about this. Ill take a look and figure out the difference and callers, and probably replace one of them tonight. I also want to get rid of the math node and replace it with native LabVIEW.

**Comment by ciozi137** [comment]
Uh yes I saw your bookmark later on

**Comment by Monkeymerlot** [comment]
Bezier Curve.vi
Callers: Funnel Path Points
Connector Pane:
![image](https://user-images.githubusercontent.com/37567672/85079436-d54b9d00-b194-11ea-8fd1-fd07e11162e7.png)

Bezier.vi 
Callers: Path to Commands.vi, Path Points.vi
Connector Pane:
![image](https://user-images.githubusercontent.com/37567672/85079410-bfd67300-b194-11ea-81ed-132fc0fae750.png)

**Comment by Monkeymerlot** [comment]
The block diagrams are also identical. I removed and replaced Bezier Curve.vi with Bezier.vi
