### ISSUE TITLE
Rename Main_v4.vi

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#14]
Main.vi?
Lithography.vi?
AFM-Lithography.vi?
General-AFM-Lithography.vi?

**Comment by Monkeymerlot** [comment]
I think this is dependent of the scope of this program in the future. Do we want to use it with ebeam lithography in the future?

**Comment by ciozi137** [comment]
Uh, probably won't be used with EBL. Right now we have SVG --> AFM
What I envision for the future is:
GDSII --> EBL via Zeiss/Raith software
GDSII --> AFM via "Lithography.vi"

**Comment by Monkeymerlot** [comment]
Ok. In that case Im going to change the shown name to AFM lithography.

**Comment by Monkeymerlot** [comment]
It seems that its already named general afm lithography:
![image](https://user-images.githubusercontent.com/37567672/85080688-e2b65680-b197-11ea-8e90-73ccd91794c8.png)
Does this hold for an exe?

**Comment by ciozi137** [comment]
I think the main_v4 should at least be named main.vi. I think “_v4” is dumb. But something like AFM_Lithography.vi is even better. I can rename the exe to match

**Comment by Monkeymerlot** [comment]
Ok. Do you want to do that now, or I can rename it?

**Comment by ciozi137** [comment]
You can rename if you’re working on it. I’m cooking dinner

**Comment by Monkeymerlot** [comment]
Ok perfect. I just didnt want to lose any changes I made.

**Comment by Monkeymerlot** [comment]
Changed to AFM_Lithography.vi
