### ISSUE TITLE
Is the Data Queue Necessary?

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/AFM-Lithography#17]
Throughout the program there is a lithography data queue that I am fairly positive that isnt used for anything. I want to check to see if it is actually used, and if not I will remove it from the program.
![image](https://user-images.githubusercontent.com/37567672/85077097-83ecdf00-b18f-11ea-8603-49adb8cd03e1.png)

**Comment by ciozi137** [comment]
I’ll look into it. There was one subVI, maybe the sub panel one that had the data cluster going in. I fixed that problem but I’m pretty sure the queue was left. That being said I’m not sure if anything is ever putting stuff onto the queue. Furthermore, data structures like this should all go away in favor of SMOs and events...

**Comment by Monkeymerlot** [comment]
I agree. But before we use SMOs I think we need to cut this program down to the bare minimum ie get rid of these structures so we can figure out what we are working with. I am thinking of a few ways to refactor this and will comment shortly in Issue #16 on some options I thought of.

**Comment by ciozi137** [comment]
Yes agree about removing cruft

**Comment by Monkeymerlot** [comment]
The SubVIs that use it are the Acquired data subpanels. I have never used this VI/feature though and I dont think the elements ever get dequeued?

**Comment by ciozi137** [comment]
I don’t think it is used. It was an idea that never saw fruition I think. I
think it’s best to remove and reimplement in new architecture with smos

**Comment by Monkeymerlot** [comment]
Ok Im going to go ahead and remove the Acquired Data Subpanels, and the data queue from everything.

**Comment by Monkeymerlot** [comment]
Should be removed completely now. Also do you know if we use the 2D and 3D stuff? I know that "Render" is used but I am unsure of the other 2

**Comment by ciozi137** [comment]
Idk. Maybe @aditi-nethwewala or @Yh-lab  can comment

**Comment by aditi-nethwewala** [comment]
I will have a look at it today and check, but I think @Yh-lab might have better idea

**Comment by aditi-nethwewala** [comment]
I am not sure if you are asking about data queue or 2D/3D stuff. I have never used the Feedback 2D/3D View feature on front panel and I don't think anyone does currently. I went through the block diagram for data queue thing. Though it is implemented in several places, I am not sure if it is doing anything

**Comment by Monkeymerlot** [comment]
I was asking about the 2D/3D stuff. We figured out the queue already (that feature was never implemented). And if we dont use it I am going to remove that functionality (we are currently trimming the fat off of this program so we can start to re-architect and add new features)

**Comment by Monkeymerlot** [comment]
Removed unused 2D and 3D feedback functionality in commit e246184
