### ISSUE TITLE
IMAQ Control for Front Panel

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/AFM-Lithography#18]
The IMAQ control is pretty ugly. I don't think that we actually need one, but I think that it would be wise to ask if anyone uses any of the IMAQ features. If not, or if they use things like the zoom feature (which is easily made in native LabVIEW), then I think that we should replace it with a picture control. It looks  a lot better and removes a distracting side bar that we (probably) don't use.

![image](https://user-images.githubusercontent.com/37567672/85093042-1f467a00-b1b9-11ea-9632-fd0f16335779.png)
![image](https://user-images.githubusercontent.com/37567672/85093267-c5927f80-b1b9-11ea-8096-656980f5dc9e.png)

**Comment by ciozi137** [comment]
## IMAQ Control features:
![image](https://user-images.githubusercontent.com/26659428/85134007-c81cc580-b209-11ea-80b5-dce92189fe99.png)
https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z000000P7klSAC&l=en-US

## _IF_ we need the toolbar we can make it look nicer:
### Image Display (Classic) with Transparent Borders:
![image](https://user-images.githubusercontent.com/26659428/85134446-85a7b880-b20a-11ea-925b-6d8cfa34ed06.png)

### Image Display (Silver) with Transparent Borders:
![image](https://user-images.githubusercontent.com/26659428/85134479-91937a80-b20a-11ea-88a6-647959390dd0.png)


### Image Display (Silver) with Transparent Borders, hide scrollbars & image info:
![image](https://user-images.githubusercontent.com/26659428/85134562-b4be2a00-b20a-11ea-9a14-133df568b726.png)

**Comment by Monkeymerlot** [comment]
What about JKI Flat UI 2.0 + IMAQ:
![image](https://user-images.githubusercontent.com/37567672/85170302-2e6e0c00-b23b-11ea-9448-3fbeae19cf29.png)

**Comment by Monkeymerlot** [comment]
After a poll, it seems the IMAQ control with reduced functionality as shown above is still needed. This is the current iteration:
![image](https://user-images.githubusercontent.com/37567672/85190830-2093a780-b28a-11ea-843a-89a22efa3151.png)
