### ISSUE TITLE
Image related bug when switching AFMs, changing to new files etc.

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/AFM-Lithography#19]
The bug occurs in "IMAQ to LV Image.vi", which is called in the "Litho Refresh Render" state:
![image](https://user-images.githubusercontent.com/37567672/85093606-c0820000-b1ba-11ea-863b-730507421b26.png)
We don't see this bug when this state is called in Macro: Initialize, so I think it has something to do with switching data when the reference exists? 
![image](https://user-images.githubusercontent.com/37567672/85093696-f58e5280-b1ba-11ea-8565-2bc968cb2b33.png)

**Comment by Monkeymerlot** [comment]
It is because of the disable diagram structure in the timeout case: 
![image](https://user-images.githubusercontent.com/37567672/85171635-60806d80-b23d-11ea-953d-7b01f2d8877f.png)
which was writing a null value to the reference. The key was that it did not happen during macro initialize. We are going to get rid of the 2D feedback feature, so this wont be a problem anymore...

**Comment by ciozi137** [comment]
oops. thanks for fixing @Monkeymerlot

**Comment by Monkeymerlot** [comment]
@ciozi137 I only recognized it because I once spent 2 days trying to debug an SMO whose class references turned to null going through a disable diagram structure. I might make a VI Analyzer plugin to detect this issue.
