### ISSUE TITLE
IMAQ Control Poll

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#20]
Do you use any of the IMAQ control features shown here:
![image](https://user-images.githubusercontent.com/26659428/85135164-ad4b5080-b20b-11ea-922f-77c83042bb35.png)
In particular, any of these tools on the toolbar:
![image](https://user-images.githubusercontent.com/26659428/85135215-c6540180-b20b-11ea-977d-5e715f99fa92.png)

/polls "Yes" "No" "I don't know"

**Comment by ymq526** [comment]
Zoom and pan

**Comment by Nina-YDY** [comment]
Yes, tools, image, scrollbars, cursor. Tools: zoom and pan.

**Comment by johnbrickmaier** [comment]
scrollbars, zoom, and pan

**Comment by aditi-nethwewala** [comment]
tools: zoom,selection, pan, point
image
cursor

**Comment by Monkeymerlot** [comment]
Thanks everyone for your replies!
