### ISSUE TITLE
Use Variant Attributes + Enum to Capture Voltage/Speed Schedule

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/AFM-Lithography#24]
Currently, we have these huge monster clusters that make it very difficult to work with the program.  Here is a picture of it:
![image](https://user-images.githubusercontent.com/37567672/85323039-535dbb80-b495-11ea-9361-912ea19ae050.png)
To make matters worse, only a small section of these clusters can be used, as they are different options. For example, if you have a constant voltage for a section, you can't also be ramping voltage for that section. We have two of these clusters; one for voltage and one for speed. 

Instead, I think it can be done using variant attributes
![image](https://user-images.githubusercontent.com/37567672/85322547-805d9e80-b494-11ea-9803-12e3241105ca.png)
![image](https://user-images.githubusercontent.com/37567672/85322897-0d085c80-b495-11ea-8614-7ba69792e415.png)
The information is still human readable if we want to probe a wire containing it. And the contained information could change based on the value of the enum.

Let me know what you think @ciozi137

**Comment by ciozi137** [comment]
@Monkeymerlot I think this is an interesting idea. The problem I have is that the attribute data isn’t as well-defined as a cluster is. Perhaps we can have a cluster typedef define the attribute data?

**Comment by ciozi137** [comment]
Another option is to add more structure to the cluster by adding sub-clusters and so on

**Comment by Monkeymerlot** [comment]
I like the idea of the cluster typedef defining the attribute data. This will also make a smoother transition when it comes time for us to move this over to an Object Oriented architecture. And I think the problem I have with it currently is not a matter of structure but rather that we have a data type that "varies" depending on the settings. I guess it just makes sense that we could utilize a variant for this. The attributes was more of a flexibility type of thing, but I guess in this case that would be a con rather than a pro.

**Comment by Monkeymerlot** [comment]
Done with initial conversion. I will keep cleaning everything up though. 

The ramp case of the Rect Edit.vi: (Note that ramp is the most cluttered.)
![image](https://user-images.githubusercontent.com/37567672/86297569-afc58700-bbc9-11ea-8254-e979d02311dd.png)

Signal Generator (where these are read and applied to the paths)
![image](https://user-images.githubusercontent.com/37567672/86297625-d4216380-bbc9-11ea-98e2-f350f717669d.png)

Front Panel of Signal Generator (used to be huge)
![image](https://user-images.githubusercontent.com/37567672/86297649-de436200-bbc9-11ea-8e49-eee03c833e64.png)

Global Variables: ( We can actually fit them on one screen now!!)
![image](https://user-images.githubusercontent.com/37567672/86297710-04690200-bbca-11ea-95de-bee4ffb754d0.png)

**Comment by Monkeymerlot** [comment]
To make sure that everything has a value, I added a thing that will check the variant attributes, and then put in default values if there isnt any. We can later change the default values.
![image](https://user-images.githubusercontent.com/37567672/86496761-c5af8500-bd4c-11ea-9154-072d2260b5b2.png)

**Comment by Monkeymerlot** [comment]
Tested and it looks good to me. Im going to close this.
