### ISSUE TITLE
Use Refactored Asylum Driver

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/AFM-Lithography#25]
Previously I refactored a driver for the Asylum microscopes (MFP-3D and Cypher). There are only a few things that I need to do to finish this driver, and then I think it can be a replacement. I also want to redo the way that we call drivers and swap them. Here are the main things that I see that are bad practices and I should change when adding the new driver.

First, is that we send information by changing values on their front panels using named controls:
![Current current way to send information to driver](https://user-images.githubusercontent.com/37567672/85326472-58be0480-b49b-11ea-88f9-862dffcd37eb.png)
Instead we should user User Events. 

Second, we currently abort VIs when swapping them inside of a subpanel and at the end. There is a better way to do this: First thing is that you don't need to abort a VI to take it out of a subpanel. Second thing is, you should never abort a VI period. Like ever. There are a few instances when you might have to as a last resort, but you should set up a way to stop them gracefully to begin with.
Where we abort subpanel
![Current method of swapping subpanels that aborts them](https://user-images.githubusercontent.com/37567672/85326569-8145fe80-b49b-11ea-8439-c8b94648dd5f.png)
Current method of swapping a subpanel:
![Swapping Subpanels](https://user-images.githubusercontent.com/37567672/85326798-d8e46a00-b49b-11ea-9cd3-b677d46a79a9.png)
So to implement this I think that it would be beneficial to think about having a User Event that will send a stop request. We can wait on some conformation that the VI has stopped. If it has not stopped in a certain amount of time, we can then abort it.

Other, less problematic issues (for now)
Use of a global variable for information such as offset and the like.

**Comment by Monkeymerlot** [comment]
Going to use a Driver Management class. 
Here is the start up routine:
![image](https://user-images.githubusercontent.com/37567672/85347672-3fcb4880-b4c7-11ea-81a8-a18de9f7e777.png)
It takes an array of paths to the drivers, and for each one it will start them, and initialize a cluster of events created for each driver. I initially wanted to do call by reference, but this wasnt possible as we dont have a set front panel where everything is based off of the same interface. For now, I think that setting the event cluster, which is named very uniquely, will suffice. 
Front Panel of Refactored Driver:
![image](https://user-images.githubusercontent.com/37567672/85347827-ca13ac80-b4c7-11ea-9a29-7313f1af21d1.png)
Creation of Events in start up routine:
![image](https://user-images.githubusercontent.com/37567672/85347902-f8918780-b4c7-11ea-967e-8b1d3e36b94a.png)

**Comment by Monkeymerlot** [comment]
Shut down flow:
![image](https://user-images.githubusercontent.com/37567672/85354753-45ca2500-b4d9-11ea-9755-c8c4a80225c8.png)
Send Stop Event to all drivers
![image](https://user-images.githubusercontent.com/37567672/85354798-57abc800-b4d9-11ea-8ea3-5fa6f87a6b8b.png)
Give them one second to stop:
If they stop in one second: Do nothing
If they don't stop in time: Consider them hanging, abort them:
![image](https://user-images.githubusercontent.com/37567672/85354831-685c3e00-b4d9-11ea-99d3-66470732dc69.png)
Destroy all User Events
![image](https://user-images.githubusercontent.com/37567672/85354868-79a54a80-b4d9-11ea-8e3e-d585992bc4c9.png)
Destroy all VI References
![image](https://user-images.githubusercontent.com/37567672/85355013-c557f400-b4d9-11ea-94cf-59b1d5f69048.png)

**Comment by Monkeymerlot** [comment]
Added functionality to embed into a subpanel:
![image](https://user-images.githubusercontent.com/37567672/85356924-34374c00-b4de-11ea-975a-c277d8eeb91d.png)
And I envision its usage like so:
![image](https://user-images.githubusercontent.com/37567672/85356854-07833480-b4de-11ea-83e3-fb029a6a1a1a.png)

**Comment by Monkeymerlot** [comment]
Added steps that are performed after each object is performed. It will write the tip voltage to be zero, and then will move the tip upwards.
![image](https://user-images.githubusercontent.com/37567672/85962826-c331e180-b980-11ea-89a8-091488052533.png)

**Comment by Monkeymerlot** [comment]
Investigation of the lithography program has revealed that the data is sent to the drivers in units of um. To do otherwise would require a significant overhaul in the program it seems.
So here it writes the inkscape ratio:
![image](https://user-images.githubusercontent.com/37567672/85963739-13ab3e00-b985-11ea-9f51-ef80f3ca7622.png)
If the size of the image is greater than 100x100 (ie 100x100 um) then it is actually nm, and the ratio is 1000. If it is less than 100x100 um, then it is determined to be in um, not nm, and its ratio is simply 1.
It reads it in the Paths Apply Inkscape Ratio:
![image](https://user-images.githubusercontent.com/37567672/85963684-dd6dbe80-b984-11ea-9729-8ed73ec3ea61.png)
and Rectangle Apply Inkscape Ratio:
![image](https://user-images.githubusercontent.com/37567672/85963704-efe7f800-b984-11ea-9889-0cbdae352e85.png)

**Comment by Monkeymerlot** [comment]
The timing seems to be 50 kHz in the old driver, so I think that its ok to use that value in the new driver as well.
![image](https://user-images.githubusercontent.com/37567672/85963846-80263d00-b985-11ea-9816-8cefcece590d.png)

**Comment by Monkeymerlot** [comment]
Abort functionality:
## Driver:
In Litho Objects:
![image](https://user-images.githubusercontent.com/37567672/86065521-d060d600-ba3d-11ea-8489-79221b3e89e7.png)
Normally we would have used OpenG Wait (ms), but instead we wait with abort in Litho Object Points:
![image](https://user-images.githubusercontent.com/37567672/86065561-e5d60000-ba3d-11ea-91be-858fca4b7d06.png)
And if Abort Notifier is True:
![image](https://user-images.githubusercontent.com/37567672/86066075-271adf80-ba3f-11ea-9233-21cc7038bb04.png)
We send a stop command to the software, and then give it a second.
Heres how we get the abort Abort Notifier Event to Provide Reference to driver.
![image](https://user-images.githubusercontent.com/37567672/86065642-25045100-ba3e-11ea-9d96-7e6954abfb9b.png)
## AFM_Lithography.vi:
Run button Event will call this code:
![image](https://user-images.githubusercontent.com/37567672/86065811-917f5000-ba3e-11ea-8391-b9741344e560.png)
Where we create notifier and send it to the driver:
![image](https://user-images.githubusercontent.com/37567672/86065869-ad82f180-ba3e-11ea-9af2-b579025bd1aa.png)
If we then hit "Abort" button while lithography is running:
![image](https://user-images.githubusercontent.com/37567672/86065910-c8556600-ba3e-11ea-817c-cccf378094df.png)
And once lithography is finished and we get the Lithography Done Event:
![image](https://user-images.githubusercontent.com/37567672/86065973-e7ec8e80-ba3e-11ea-9594-1152d71b9039.png)


I hope this makes sense.

**Comment by Monkeymerlot** [comment]
Added Resistor Box with help from @johnbrickmaier and put post object stuff in terminateLithographyObject
![image](https://user-images.githubusercontent.com/37567672/86272196-2d729e00-bb9c-11ea-8b98-c2cc7c340837.png)
Added event call back to post object stuff:
![image](https://user-images.githubusercontent.com/37567672/86272286-4f6c2080-bb9c-11ea-8b46-6b03b25f591b.png)
Added abort for initial move:
![image](https://user-images.githubusercontent.com/37567672/86272363-74609380-bb9c-11ea-91ea-ea3831ee1f73.png)
Fixed bug involving speed on move to initial point (wasnt orignally written, making it zero, thus dividing by zero gave inf, which was the time we would have waited for...)
![image](https://user-images.githubusercontent.com/37567672/86272537-b8539880-bb9c-11ea-83a9-315fd404f766.png)

Monitored commands and everything looks good. Ready for second code review.

**Comment by ciozi137** [comment]
@Monkeymerlot I'm looking at things now and preparing test build. There are some issues with files being in weird places and the Asylum Driver project is inside the AFM Litho project (issues #34 #32 ?)
Maybe we should switch to autopopulating folders...?

**Comment by Monkeymerlot** [comment]
I think the Asylum Driver Project is because of the autopopulating folder. We can take that out. Everything _should_ be in the right place, but you and I know that with LabVIEW and source control that only happens when the stars align ¯\_(ツ)_/¯

**Comment by Monkeymerlot** [comment]
![image](https://user-images.githubusercontent.com/37567672/86635676-626a6080-bfa1-11ea-925b-426394af3264.png)
Minor change. I made the move to initial point speed be equal to the value in the old program

**Comment by Monkeymerlot** [comment]
Reviewing over the command order. I think that tip down should happen _after_ the move to the initial point?
![image](https://user-images.githubusercontent.com/37567672/86636294-1ec42680-bfa2-11ea-8a9e-71a6572fb572.png)

**Comment by Monkeymerlot** [comment]
@ciozi137 I saw that you did a build. I just wanted to make sure that you turned Debug? to False on the driver:
![image](https://user-images.githubusercontent.com/37567672/86637676-fccba380-bfa3-11ea-961f-5c8833932486.png)

**Comment by ciozi137** [comment]
don't know. I will check

**Comment by ciozi137** [comment]
no. it was true. I will fix in v8.6.0.5

**Comment by ciozi137** [comment]
Still building 8.6.0.5. It's taking a really long time for the installer for some reason. Will have to come back later to check and commit/push my changes.

**Comment by ciozi137** [comment]
That build was terrible. Starting over. Will be 8.6.0.7.

**Comment by ciozi137** [comment]
@Monkeymerlot @aditi-nethwewala new build 8.6.0.7 is posted. Code is pushed also

**Comment by Monkeymerlot** [comment]
Reported issue:
(@aditi-nethwewala)
1. It created a duplicate version of LV 2020 which led to all the programs freezing for the next user. I ultimately had to restart the computer while someone was in between their experiment
2. After the restart, somehow the lithography got a little messed up. 
The tip started going to 0,0 position at the start of the writing instead of starting from its last position. I could only get rid of it by uninstalling the exe version.

**Comment by Monkeymerlot** [comment]
![image](https://user-images.githubusercontent.com/37567672/105927064-37b12980-6011-11eb-855f-1c79a85976db.png)
Got this issue when I was running a built version of the program.

**Comment by Monkeymerlot** [comment]
With the new build, this should be ready for testing. Hopefully, everything is now in order and should work.

**Comment by Monkeymerlot** [comment]
@ciozi137  I think we can close this issue out (finally)?
