### ISSUE TITLE
Template for New Drivers

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/AFM-Lithography#27]
We should make a template for new drivers for different AFMs that is compatible with the AFM_Driver_Manager class.

**Comment by ciozi137** [comment]
Do you mean a literal .vit template?

**Comment by Monkeymerlot** [comment]
Yeah with a JKI State Machine, and event cases for all of the events + a uniform background color etc and the event cluster on the front panel with the proper name. Once I get the asylum VIs working I want to start adding things like the nanosurf etc.

**Comment by Monkeymerlot** [comment]
Made a template with basic states, events registered, front panel correctly sized, etc. 
AFM_Name_Driver.vit:
![image](https://user-images.githubusercontent.com/37567672/86284420-e04cf700-bbb0-11ea-9670-f029c020111c.png)
