### ISSUE TITLE
IMAQ Flicker on Update

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/AFM-Lithography#28]
IMAQ is by reference, so if you change things using that reference, it will update in real time. This can cause some flicker. See this gif: (edit: you cant see flicker in gif because frame rate is too low, so I removed it)

There are a few ways to resolve this issue. First, is by delaying front panel updates until the entire operation is done. Second, is making a copy of the reference using IMAQ Copy.vi, work using this copied reference, and then at the end update the indicator with the new backend reference. I am not sure which one of these would be best so I am open to ideas and suggestions.

**Comment by ciozi137** [comment]
Are you saying that even if the image is updated in an “UI: update” state it will still have flicker, because the imaq image is updated by ref?
Delaying front panel updates blight be a good way to go. Would that be driven by the timeout frame?

**Comment by Monkeymerlot** [comment]
I think the reason it flickers is because we write the background image, then the overlay. 
So it goes Image + overlay ->image->image + overlay. 
I did some investigating and I think that it would just be best to create a new reference, work with that, then write it to the imaq indicator, and then close the original reference.

**Comment by Monkeymerlot** [comment]
I fixed this by working with a "work" reference and then copying over to the IMAQ control, which is in its own state now:
![image](https://user-images.githubusercontent.com/37567672/86174085-04480400-baef-11ea-9369-02a9db9eb975.png)

Refresh Render:
![image](https://user-images.githubusercontent.com/37567672/86174111-10cc5c80-baef-11ea-90aa-f2142ebca1bc.png)
Display Background:
![image](https://user-images.githubusercontent.com/37567672/86174131-1aee5b00-baef-11ea-95eb-e7953d38446c.png)
Data Initialize:
![image](https://user-images.githubusercontent.com/37567672/86174176-2d689480-baef-11ea-9041-ada05dd0503b.png)
