### ISSUE TITLE
Why factor of 50000?

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#29]
MFP3D XPT Schematic shows 100kHz DACs:
![image](https://user-images.githubusercontent.com/26659428/86047328-b9f65280-ba1c-11ea-9bec-3b7260ec0f1c.png)

Other documentation (https://mmrc.caltech.edu/Asylum/Manuals/Asylum%20MRP-3D%20manual.pdf) mentions 52 kHz LPF on User OutA and OutB:

"User DACs:  OutA, OutB, and OutC Each of the three User DAC channels originates at a 24-bit 100kHz User DAC and terminates at a Xpnt Input.  Each channel’s User DAC can generate signals ranging anywhere in magnitude within the +/-10V limits.  The OutA and OutB data channels both pass through a 52 kHz LPF, which caps their signal’s highest possible frequency to approximately this value; their signal’s lowest possible frequency is DC.  The OutC data channel is filtered to a mere 78Hz LPF thereby rejecting higher frequency noise components and making it the best channel for a low noise DC voltage source.

"While the OutA and OutB data channels are not often utilized by the software, the OutC data channel is occasionally used for applying DC biases (e.g. to the cantilever tip as in EFM)."

**Comment by Yh-lab** [comment]
As far as I can remember it is inside the documentation of Asylum program. I will try to find it.

**Comment by Monkeymerlot** [comment]
Has anyone figured this out yet?

**Comment by Monkeymerlot** [comment]
X and Y PID loops are 50 kHz, not necessarily Output A that is the limiting factor. From the Asylum Software Manual (page 189):
![image](https://user-images.githubusercontent.com/37567672/158900971-b330292e-e4d7-4ffd-aba5-2201caf327da.png)
