### ISSUE TITLE
Change startup read image paths

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#3]
When the software starts it tries to load files according to preset front panel controls. If the file is not present the software halts. We need to change the way the files are defined (configuration file?) and give user opportunity to choose the file before crashing. Even though we now have an exe version (https://github.com/levylabpitt/AFM-Lithography/releases/latest) it is useless because of this issue.

![image](https://user-images.githubusercontent.com/26659428/84695234-85f93880-af18-11ea-83d2-dacb73f480db.png)

**Comment by Monkeymerlot** [comment]
This is probably what I would do:
![image](https://user-images.githubusercontent.com/37567672/84698763-5f3e0080-af1e-11ea-9a76-e35998186ab0.png)
If it exists, then just use that path.

**Comment by ciozi137** [comment]
looks good

**Comment by ciozi137** [comment]
What about adding a button called "load files"? That way the user can reload files...or choose when at startup to load the files.

**Comment by Monkeymerlot** [comment]
I think that the refresh button does what you are talking about. Can you elaborate a bit on what you had in mind?

**Comment by ciozi137** [comment]
Yes I checked it earlier and the refresh button does load the files. I think adding your check before the files are loaded would be good. That way we can avoid the error pop ups. And maybe add a green light on the front panel indicating when the files are loaded?

**Comment by Monkeymerlot** [comment]
Would this green light occur before or after parsing?

**Comment by ciozi137** [comment]
@Monkeymerlot I added your changes into my working copy. It looks good except the file check is returning "true" even for the path "c:\". I will keep looking at it.

Regarding the green light I was thinking after parsing...but it looks like the "ready" light already accomplishes this.

**Comment by ciozi137** [comment]
![image](https://user-images.githubusercontent.com/26659428/84806948-80612880-afd4-11ea-9044-5608e29246ed.png)

**Comment by Monkeymerlot** [comment]
We could also just check their extensions and make sure that they are the correct file type...

**Comment by ciozi137** [comment]
agree...we can also do this
