### ISSUE TITLE
Sign exe and installer?

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#30]
https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z0000004A62SAE&l=en-US

@Monkeymerlot see above link how to sign applications and installers. I don't think we should do this. Mostly because we need to purchase a certificate from Verisign.

**Comment by Monkeymerlot** [comment]
Agreed. The only people using this software will probably know us or be us. If it was free it'd be worth spending some time on but not for $250.

https://www.geocerts.com/code-signing-certificates

**Comment by Monkeymerlot** [comment]
The university might have one that we could use: https://www.technology.pitt.edu/security/digital-certificates
