### ISSUE TITLE
Event.ctl error

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#32]
![image](https://user-images.githubusercontent.com/26659428/86360445-63695e00-bc40-11ea-9f1f-4f207934b27d.png)

in latest build bb48a78

**Comment by ciozi137** [comment]
@Monkeymerlot I disconnected Events.ctl from the class and also moved added it to the project:

![image](https://user-images.githubusercontent.com/26659428/86361010-349fb780-bc41-11ea-8cf5-0e462ecbdcad.png)

I think this probably isn't quite right yet.

**Comment by ciozi137** [comment]
Actually this might be related to me not having the Asylum API package installed before. That being said I think it would be good to remove the Asylum driver project from the AFM_Lithogaphy project:

![image](https://user-images.githubusercontent.com/26659428/86365330-5ef47380-bc47-11ea-8a71-41c7347fe100.png)

**Comment by Monkeymerlot** [comment]
No I moved it into the library later in development.. It didnt give me any issues at the time. I should have removed it from the project, then right clicked, Add>File and selected it. Ill fix this.

But you should also install the latest version of the Asylum-API

**Comment by Monkeymerlot** [comment]
@ciozi137 Try it now...

**Comment by ciozi137** [comment]
https://github.com/levylabpitt/AFM-Lithography/issues/35#issuecomment-653172085

**Comment by ciozi137** [comment]
@Monkeymerlot there doesn't seem to be any files called "Asylum_Driver.vi" in the Asylum_API package. I'm going to kick this back to you: you can remove the "Asylum Driver" stuff from the Litho project. Actually I think you should delete them from the entire repository, and then you can fix any missing files etc in the Asylum_API project.

**Comment by Monkeymerlot** [comment]
Nooooo... they are different. See latest comment in #34

**Comment by Monkeymerlot** [comment]
The event.ctl issue should be fixed.
