### ISSUE TITLE
MFP3D_Lucy?

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#33]

**Comment by Monkeymerlot** [comment]
Never used it. @Yh-lab might know? Anyways, I think that the new driver should replace it as well.

**Comment by ciozi137** [comment]
I propose we delete it from the source code when we remove Cypher and MFP3D

**Comment by Yh-lab** [comment]
I think we can remove it. It only involves a small change about engaging or withdrawing the tip which doesn't really affect the writing.

**Comment by Monkeymerlot** [comment]
This will be removed once we finish revisions on the new driver.
