### ISSUE TITLE
Error 1003

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#34]
![image](https://user-images.githubusercontent.com/26659428/86365601-b85ca280-bc47-11ea-8855-b0631d3c4e46.png)

**Comment by ciozi137** [comment]
Asylum_Driver.vi not executable:

![image](https://user-images.githubusercontent.com/26659428/86368888-beed1900-bc4b-11ea-875f-257aa752e6da.png)

**Comment by ciozi137** [comment]
![image](https://user-images.githubusercontent.com/26659428/86369083-f8258900-bc4b-11ea-8eaf-f0cc89cd7cdf.png)

**Comment by Monkeymerlot** [comment]
Debug mode was added in the latest release of the Asylum API

**Comment by ciozi137** [comment]
https://github.com/levylabpitt/AFM-Lithography/issues/35#issuecomment-653172085

**Comment by Monkeymerlot** [comment]
@ciozi137  are you still getting this issue?

**Comment by ciozi137** [comment]
Uh don’t know. another issue cropped up with the relay box.

![image](https://user-images.githubusercontent.com/26659428/86500316-3c08b300-bd5e-11ea-958f-019f07d49b38.png)

**Comment by Monkeymerlot** [comment]
Hmm @johnbrickmaier do you know what the cause of this might be?

**Comment by ciozi137** [comment]
I suspect something like missing C++ Runtime. I'm investigating

**Comment by ciozi137** [comment]
I re-downloaded the dll ftd2xx.dll and replaced mine. Who knows... I think this is worked out on the machines actually running the Relay Box
