### ISSUE TITLE
AFM Type

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#35]
Only one is shown:

![image](https://user-images.githubusercontent.com/26659428/86365727-e2ae6000-bc47-11ea-92ba-8f53dff2349f.png)

**Comment by ciozi137** [comment]
OK I see that Asylum is the only one available now.

![image](https://user-images.githubusercontent.com/26659428/86365883-1d17fd00-bc48-11ea-8412-9b40b803ea4f.png)

@Monkeymerlot Does simulation more work?

**Comment by Monkeymerlot** [comment]
No. But the newest release of the Asylum API will open up a debug window which will show all of the commands happening in real time. I am unsure of what the simulation mode actually did as I never used it. You will need the latest release of the Asylum-API package for debug mode and to rewire the wire in #34 .

**Comment by Monkeymerlot** [comment]
Also @ciozi137 , something isn't right with those funnels. Probably had to do with the work I did on the TypeDefs last night.

**Comment by ciozi137** [comment]
OK I didn't know Asylum-API had an update. I will grab it and then load on our package server later

**Comment by Monkeymerlot** [comment]
I think I just forgot to tell you. My bad... It should just be the latest in the builds folder.

**Comment by ciozi137** [comment]
Yeah I found it

**Comment by Monkeymerlot** [comment]
Ok let me know if you still have this issue. I am having issues with the reference to the asylum driver on my computer so I need that functionality to develop the driver without it blowing up with errors.

**Comment by ciozi137** [comment]
@Monkeymerlot I'm confused about the folder "Asylum_Driver" in the AFM_Lithography project vs the Asylum API:

![image](https://user-images.githubusercontent.com/26659428/86400252-4780af00-bc76-11ea-9f69-0bd1dc2677e6.png)

Also "Asylum_Driver.vi" is still giving me an error after updating the package to v1.0.0.2.

**Comment by Monkeymerlot** [comment]
Asylum API: Low level commands that directly control the AFM. Things like td_WriteString, td_ReadValue, ir_SetPISLoop etc. These are only commands provided by asylum. Nothing more. Its a simple LabVIEW wrapper for the commands they provide us.

The ActiveX API only provides us with a single command that we use: Execute2. This just sends something to the command line. Instead, I have made Asylum API as a way to send specific commands, properly formatted, to igor. This provides a level of consistency.


Asylum_Driver: Uses these commands to do specific tasks, like move to a position, get XY Set points, Read specific values that we want. Goes through all the points in lithography etc. It is built upon these low level commands in the Asylum API package. 

Take the Nanosurf AFM as a counter example. It provides all the functionality through commands provided in the ActiveX interface. If I want to set tip voltage I would just send it through the command provided.

Here is a comparision between the three:
![image](https://user-images.githubusercontent.com/37567672/86401683-ab0bdc00-bc78-11ea-9232-34a49da7c7b2.png)
where igor is just the activeX without Asylum API

**Comment by Monkeymerlot** [comment]
@ciozi137  is it the same error?

**Comment by Monkeymerlot** [comment]
I will make a video explaining the difference between the Asylum Driver and Asylum API.

**Comment by ciozi137** [comment]
@Monkeymerlot thanks your explanation makes sense. But the icons are the same:
![image](https://user-images.githubusercontent.com/26659428/86407764-a13ba600-bc83-11ea-8824-f10fe4a8cd5c.png)

The new error is different. It might be related to the Relay Box package. Checking...

**Comment by Monkeymerlot** [comment]
Video: https://drive.google.com/file/d/1nYPE_TKi-ClADYARoeyIJR8el_A7k9lh/view?usp=drivesdk

**Comment by Monkeymerlot** [comment]
I can go in and change the icons for the driver to something else.

**Comment by Monkeymerlot** [comment]
Driver Icons are changed.

**Comment by ciozi137** [comment]
nice. i'm installing Caraya then I will check it

**Comment by ciozi137** [comment]
OK thanks. They are different, but I think can be more different. Let's add it to the todo list. I think we can also put each of these things in a class just to use as a container and easy way to update all of the icons at once

![image](https://user-images.githubusercontent.com/26659428/86408933-ecef4f00-bc85-11ea-8b86-6ca17a495676.png)
