### ISSUE TITLE
Root Path

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#36]
"Root path" is the root location in the application. We need to handle this correctly so that AFM_Lithogaphy.**vi** and AFM_Lithography.**exe** will function the same way.

![image](https://user-images.githubusercontent.com/26659428/86366237-8a2b9280-bc48-11ea-9380-05a4c07479df.png)

Here is comparison in a Test EXE.vi

![image](https://user-images.githubusercontent.com/26659428/86367459-f8bd2000-bc49-11ea-8112-572d4bb5d08f.png)

I don't know what the Application.vi is thinking.

Here is inside the built exe:

![image](https://user-images.githubusercontent.com/26659428/86367645-39b53480-bc4a-11ea-888e-d0e8471a3220.png)

This is better, but the Current VI's Path__ogtk.vi gives us the path **inside** the *.exe file, which is what I want

**Comment by ciozi137** [comment]
![image](https://user-images.githubusercontent.com/26659428/86368066-c19b3e80-bc4a-11ea-91bd-6b366f5ab53d.png)

**Comment by Monkeymerlot** [comment]
Makes sense, I will put a good explanation of what is going on in the diagram.
