### ISSUE TITLE
Test files

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#37]
Test paths should be relative to the project/application:
example:
![image](https://user-images.githubusercontent.com/26659428/86370111-4b4c0b80-bc4d-11ea-8e47-e43e419361d0.png)

**Comment by Monkeymerlot** [comment]
Oh sorry this was just for my own testing. I probably should convert this into unit tests with a "Unit_Test_Driver". That way we can make changes confidently in the future without having to worry about breaking it.

**Comment by Monkeymerlot** [comment]
Unit test driver is made. 
![image](https://user-images.githubusercontent.com/37567672/86408496-1a87c880-bc85-11ea-8911-67e99143d5e6.png)
Redid the Calling VI:
![image](https://user-images.githubusercontent.com/37567672/86408603-46a34980-bc85-11ea-9baf-7d8fecdbb3b0.png)
