### ISSUE TITLE
Watchdog VIs?

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#40]
@Monkeymerlot 
### when I do a mass compile of this repository I get these errors:
![image](https://user-images.githubusercontent.com/26659428/86625009-5b882180-bf92-11ea-9f93-d0017f162f54.png)

### None of those 6 VIs are in the AFM_Driver_Manager.lvclass:
![image](https://user-images.githubusercontent.com/26659428/86625153-9f7b2680-bf92-11ea-9621-1ef0c2fa8598.png)

### And they have other errors, like they are looking for data on the class wire that isn't there?
![image](https://user-images.githubusercontent.com/26659428/86625207-b6ba1400-bf92-11ea-9537-a1abb21b840c.png)

**Comment by Monkeymerlot** [comment]
That was an overly complicated way that I initially tried to implement the abort sequence. You can delete all of them.

**Comment by ciozi137** [comment]
Awesome. I love to lighten the load

**Comment by ciozi137** [comment]
How about:
AFM_Driver_Manager.SendBackgroundImage.vi
AFM_Driver_Manager.SendLithography.vi
AFM_Driver_Manager.SendRun.vi
AFM_Driver_Manager.SetActive.vi

They don't have callers

**Comment by ciozi137** [comment]
Also
Abort
CreateAbort
DestroyAbort

**Comment by ciozi137** [comment]
Also

- GetPublicEvents
- ReadActiveDriver
- SetActive

**Comment by Monkeymerlot** [comment]
Im not sure if something is wrong with your project or what but those all have callers...
Abort:
![image](https://user-images.githubusercontent.com/37567672/86627124-c9821800-bf95-11ea-95ee-937c73e52edb.png)
Create Abort:
![image](https://user-images.githubusercontent.com/37567672/86627190-e4548c80-bf95-11ea-9940-2af3861a6c02.png)
Destroy Abort:
![image](https://user-images.githubusercontent.com/37567672/86627217-ee768b00-bf95-11ea-982a-aa7c25812624.png)
Send Background Image:
![image](https://user-images.githubusercontent.com/37567672/86627246-fd5d3d80-bf95-11ea-9a67-1e6c186dccdd.png)

And I can go on...

**Comment by ciozi137** [comment]
Oh OK I see. I think I only had the class open.
