### ISSUE TITLE
Unit_Test_Driver.vi

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#41]
### Few questions about the state machine:
![image](https://user-images.githubusercontent.com/26659428/86625994-0d741d80-bf94-11ea-8eb0-7dc5b1088436.png)

**Comment by ciozi137** [comment]
i.e.:
![image](https://user-images.githubusercontent.com/26659428/86626136-4613f700-bf94-11ea-9e27-db1a01bacde6.png)

**Comment by Monkeymerlot** [comment]
@ciozi137  because we are changing the value of those references before we start up the driver programmatically... You cant do that with a constant

**Comment by ciozi137** [comment]
But what is updating them? They aren't wired to a terminal

**Comment by Monkeymerlot** [comment]
You dont have to be wired to a terminal to update something:
![image](https://user-images.githubusercontent.com/37567672/86627394-401f1580-bf96-11ea-8502-dd92c4758b99.png)

**Comment by ciozi137** [comment]
I see
