### ISSUE TITLE
Version of LabVIEW issue?

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/AFM-Lithography#42]
@ciozi137 
![image](https://user-images.githubusercontent.com/37567672/86628153-8163f500-bf97-11ea-99df-76b35b6a655e.png)
This happened when pulling the latest 3 commits. I have LabVIEW 2020

**Comment by ciozi137** [comment]
@Monkeymerlot Sorry I didn't tell you I was using Labview 2021

**Comment by Monkeymerlot** [comment]
Im assuming that is sarcasm but I can't do anything as the whole entire library is now bricked and thus the entire program is as well. Any ideas?

**Comment by ciozi137** [comment]
Yes, /s. I'm closing and reopening. Will see what happens...

**Comment by ciozi137** [comment]
Same error here. This is amazing

**Comment by ciozi137** [comment]
Annnnd NI is closed today for the holiday

**Comment by Monkeymerlot** [comment]
@ciozi137 maybe we unlocked LabVIEW 2020 on accident. But really just thankful that it wasnt a driver or something. I just rewrote it and ran the tests:
![image](https://user-images.githubusercontent.com/37567672/86630094-621a9700-bf9a-11ea-9042-89fe7c5e5089.png)

**Comment by Monkeymerlot** [comment]
Just pushed.

**Comment by ciozi137** [comment]
same. I think it looks good now

**Comment by ciozi137** [comment]
I'm working on building "v8.6"
