### ISSUE TITLE
New IMAQ to LV function

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#44]
"I [@Monkeymerlot] rewrote the LV to IBW IBW file to LV from scratch using the Igor Technical Notes since we were unsure if we wrote it or not, and also we want a standard interface when reading files. Can you test it on a few different files to make sure everything works correctly? You will need to have IMAQ 20 installed. 

Also, can you take a look at the block diagram and see if it is readable? I have two states in the "Directory" category that provide indexes and lengths for all values in the Binary and Wave Headers, so if we want to extend it in the future we can do so, but I want to make sure that it is possible to do so when I'm gone."

**Comment by ciozi137** [comment]
@Monkeymerlot I put this file in the project (with new name "Load IBW File.vi"

I also added a "Variant LUT" to scan size VI (replaces "...ReadScanSizeAndOffset...")

Summary:
![image](https://user-images.githubusercontent.com/26659428/86930804-69aa7f00-c105-11ea-9d16-afa7af9a5a6f.png)

VIs do not refer to the new ones. And Old ones still exist in project. Once the new ones are incorporated we should remove the old files.

**Comment by Monkeymerlot** [comment]
For clarity, the file is called ReadIBWFile.vi (to match similar functions such as ReadNIDFile.vi)

**Comment by Monkeymerlot** [comment]
Sgl word wrap is incorperated into the new function and credited there.

**Comment by ciozi137** [comment]
OK you can rename.
Re: SGL word wrap, just pointing out some duplicate stuff

**Comment by Monkeymerlot** [comment]
I hadnt seen that you posted a picture and was pointing out what we are talking about for anyone viewing this in the future.

**Comment by Monkeymerlot** [comment]
And the duplicate is because I had copied over that file which wasnt part of the lithography repository at the time when refactoring the asylum driver. When integrating the new driver into the main branch I think I just forgot to remove it.

**Comment by ciozi137** [comment]
my changes are pushed if you want to take a crack at incorporating these things + deleting stuff

**Comment by Monkeymerlot** [comment]
I did some modifications to the way the benchmarking was done to make the measurements independent of the other function (you have to purposefully force the compiler to look at each function individually) and added averages.
![image](https://user-images.githubusercontent.com/37567672/86939075-20f7c380-c10f-11ea-9cd3-e6c882d730a9.png)

Results provided the same conclusion, but both functions actually performed better (values in seconds):
![image](https://user-images.githubusercontent.com/37567672/86939150-366ced80-c10f-11ea-9c89-7424c846e166.png)

**Comment by Monkeymerlot** [comment]
Ok everything is implemented and seems to work fine.

**Comment by Monkeymerlot** [comment]
Increased speed by a factor of 92%:
Old:
![image](https://user-images.githubusercontent.com/37567672/87236387-f891f280-c3b6-11ea-8703-be074c2d5512.png)
New:
![image](https://user-images.githubusercontent.com/37567672/87236393-06e00e80-c3b7-11ea-8b22-aa6b9a497bd1.png)

Basically I change the entire array at once, instead of each point (which has many buffer allocations)
