### ISSUE TITLE
Update install location

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#45]
Should be C:\Program Files (x86)\LevyLab\AFM Lithography\ and Start Menu\LevyLab\AFM
like this:
![image](https://user-images.githubusercontent.com/26659428/87190926-6d830080-c2c1-11ea-99cd-db947d41b328.png)

not this:
![image](https://user-images.githubusercontent.com/26659428/87190891-60661180-c2c1-11ea-8bed-9cac207242c9.png)

**Comment by ciozi137** [comment]
also:
![image](https://user-images.githubusercontent.com/26659428/87191050-a28f5300-c2c1-11ea-8c6e-dc2a53bf4d40.png)

**Comment by ciozi137** [comment]
@Monkeymerlot I just updated the build spec

**Comment by Monkeymerlot** [comment]
@ciozi137 Has this been finished with the new build script?

**Comment by ciozi137** [comment]
The location is specified in the project build specs in the project. The build script only produces the self-extracting installer

**Comment by Monkeymerlot** [comment]
It looks like it was correct:
![image](https://user-images.githubusercontent.com/37567672/106525647-4a64ac00-64b2-11eb-8e6e-1f349c7c84db.png)

**Comment by ciozi137** [comment]
That looks good. How about the Start Menu shortcut?

**Comment by Monkeymerlot** [comment]
@ciozi137 The shortcut menu doesn't seem to be correct. I reopened this issue until this is fixed...
![image](https://user-images.githubusercontent.com/37567672/106538752-b8b56880-64ca-11eb-86ad-37eab3226953.png)
![image](https://user-images.githubusercontent.com/37567672/106538772-c10da380-64ca-11eb-94ec-cfdfccf10f58.png)

**Comment by ciozi137** [comment]
I'll look at it tomorrow. It should be simple to fix. It can be tricky to get the shortcuts right

**Comment by ciozi137** [comment]
@Monkeymerlot just updated develop branch. There was also a merge commit, I tried to take your changes but just double check.

**Comment by Monkeymerlot** [comment]
It seems like it merged smoothly. I wasn't working on that file so we should be good.

**Comment by Monkeymerlot** [comment]
![image](https://user-images.githubusercontent.com/37567672/106811476-6005dd00-663c-11eb-908d-c6d63ecc8263.png)
It looks good now...
