### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#46]
- move to Git Flow / GitHub Flow branch model
  - Git Flow: https://nvie.com/posts/a-successful-git-branching-model/
  - GitHub flow: https://guides.github.com/introduction/flow/
-  delete/close all the other old, stale branches

**Comment by Monkeymerlot** [comment]
@ciozi137 so basically what I was using master for is really now the development branch, and every time I work on a new feature I make a branch _from_ development, where I then merge _back into_ development branch? Then for a release I would merge development into master?

**Comment by ciozi137** [comment]
Yes that’s the basic gist. The way I understand it is that **master** should always be in a working state. And development can be a mixture of not working and new features.  So whenever we make a “release” we would merge into master. I don’t know if we need to be so sophisticated to have release branches, but we could.

**Comment by Monkeymerlot** [comment]
Before I begin deleting branches Im going to download the code for Master in a zipped file just in case something wonky goes on.

**Comment by Monkeymerlot** [comment]
These are all stale but they might have significant changes on them? @aditi-nethwewala can we delete that branch or?

**Comment by aditi-nethwewala** [comment]
@Monkeymerlot the Bitmap functionality is something we tried to develop a few years ago. We never really moved forward on them, but it has significant differences from the main program. I would suggest not to delete them, if required they can be moved elsewhere

**Comment by ciozi137** [comment]
Deleting the branch won't delete the files. It just deletes the pointer to the branch. We can always get the files by checking out an old revision.

**Comment by Monkeymerlot** [comment]
Ok then I will delete the branches tomorrow or on Monday, and if we need the code later we can go and check out the old revisions.

**Comment by Monkeymerlot** [comment]
Branches are cleaned up
![image](https://user-images.githubusercontent.com/37567672/87329305-b8d92100-c504-11ea-8fba-fd97f22f9b22.png)
