### ISSUE TITLE
Cannot Rearrange Patterns (drag-and-drop reorder)

### ISSUE THREAD

**Issue by aditi-nethwewala** [levylabpitt/AFM-Lithography#49]
![image](https://user-images.githubusercontent.com/61893772/87227942-053d2900-c36c-11ea-9efb-7446e564164d.png)

**Comment by Monkeymerlot** [comment]
I will fix this in the repository but for now you can do the following to the non exe on the computer:
1. Right click on the listBox control
2. Select "Drag and Drop"
3. Make sure that both "Allow Dragging" and "Allow Dropping" are selected.
![image](https://user-images.githubusercontent.com/37567672/87233944-287ecd00-c39a-11ea-8af6-75116212f64f.png)



To fix the exe we will have to build it again, so this will probably be fixed sometime this week for the exe.

**Comment by Monkeymerlot** [comment]
Fixed programmatically (so changing control again wont change this functionality without breaking code) in develop
