### ISSUE TITLE
Add save/load front panel configuration

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#5]
- Front panel controls (**particularly file paths**) should be saved/loaded to config file
- Use Configuration read/write from Instrument Framework class
- C:\ProgramData\Levylab\AFM Lithography\config.ini

**Comment by ciozi137** [comment]
@edanalpern any progress on this? Do you want to discuss sometime?

**Comment by edanalpern** [comment]
@ciozi137 No and yes! Haven't looked at it since you created the task....

Is there an existing config file?  Or is the idea to create one and save it in the directory you listed?

What is instrument framework class?

**Comment by ciozi137** [comment]
Let's talk about this later this morning. 10am?

**Comment by edanalpern** [comment]
Our Solid state reading group meets then. 11:30am or anytime after, I am available. How's 11:30am?

**Comment by ciozi137** [comment]
Ok 11:30

**Comment by Monkeymerlot** [comment]
@edanalpern Im not sure if you have been actively pulling from main branch when you work, but if not, lets meet and discuss/implement your changes directly on master so we dont have a merge batte.

**Comment by edanalpern** [comment]
@Monkeymerlot  I pulled from the master branch just this morning,  so I don't think it will be an issue.

**Comment by Monkeymerlot** [comment]
I have made 10 commits since this morning

**Comment by edanalpern** [comment]
Oh, see. I'm messaging you on google hangouts.

**Comment by Monkeymerlot** [comment]
Implemented in commit 3b6b055:
New states:
![image](https://user-images.githubusercontent.com/37567672/86181013-3d867100-bafb-11ea-8d95-54ecec5e6bf0.png)

Data: Initialize:
![image](https://user-images.githubusercontent.com/37567672/86181043-4aa36000-bafb-11ea-9dc0-41ec785d8b02.png)

Macro: Initialize (Caller of Initialize and Read):
![image](https://user-images.githubusercontent.com/37567672/86181098-66a70180-bafb-11ea-9c50-180c36b3c679.png)

Macro: Exit (Caller of Write):
![image](https://user-images.githubusercontent.com/37567672/86181181-8a6a4780-bafb-11ea-9c74-cb2c05bfd4da.png)

Configuration: Write:
![image](https://user-images.githubusercontent.com/37567672/86181207-9524dc80-bafb-11ea-86cf-bf2ca448750e.png)

Configuration: Read:
![image](https://user-images.githubusercontent.com/37567672/86181232-a0780800-bafb-11ea-9225-9be98b4efc5d.png)

Configuration: Initialize:
![image](https://user-images.githubusercontent.com/37567672/86181259-aec62400-bafb-11ea-9635-22847e2887bc.png)

**Comment by ciozi137** [comment]
I like it. Simple. We can add more configuration parameters as needed
