### ISSUE TITLE
Enable disable tabs not clear

### ISSUE THREAD

**Issue by aditi-nethwewala** [levylabpitt/AFM-Lithography#50]
The older switch was better

![image](https://user-images.githubusercontent.com/61893772/87227964-2b62c900-c36c-11ea-9bfa-3c85dd8e7ad0.png)

**Comment by Monkeymerlot** [comment]
I will fix this in the near future. For now though, filled/grey = True, unfilled/white = False.

**Comment by Monkeymerlot** [comment]
I think that a "switch" type of button might render this a little bit more clear while staying away from "The ugliest button in LabVIEW":

![image](https://lh3.googleusercontent.com/r0pCV2CAoi4lCwtJNo4S3UpA4SehUUB48Wpe2QGexCQAWFYfe0j8VRjTrMjFh36weNqbHngUlt6TY770Mk0TnMPIMRbGn-5RTp7pYw=w1064-v0)
Source: https://material.io/components/selection-controls#switches

**Comment by Monkeymerlot** [comment]
@aditi-nethwewala is this more clear?
![image](https://user-images.githubusercontent.com/37567672/87235337-25d7a400-c3a9-11ea-99ac-23a86a1f8e9b.png)
 or even this:
![image](https://user-images.githubusercontent.com/37567672/87235398-c1691480-c3a9-11ea-81b1-28d5e5386337.png)

**Comment by aditi-nethwewala** [comment]
I think this is better

![image](https://user-images.githubusercontent.com/61893772/87236673-f9785380-c3b9-11ea-91d3-4db6bbc79505.png)

**Comment by Monkeymerlot** [comment]
Ok that should be easy to implement.

**Comment by Monkeymerlot** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/37567672/87238653-6ba96200-c3d3-11ea-84ab-4a869af3e6ab.png)
