### ISSUE TITLE
Done tab closes the exe. completely

### ISSUE THREAD

**Issue by aditi-nethwewala** [levylabpitt/AFM-Lithography#51]
Done function is used under few cases:

To stop the lithography in between ( I think we discussed making abort button functional regarding this)
Once we are done using the AFM
Sometimes before writing the barriers, we need to press done and restart the program, otherwise the program does not respond to making the small barriers properly (ot sure why, can be interpolation distance problem too or something else)

**Comment by Monkeymerlot** [comment]
Re Cases:
1. Abort should do this properly now, but you will need to test it.
2. This is when this function should be used. The program should stop and exit. Closing the exe completely is the expected functionality in this case. In the development environment, it is expected to finish and stop execution.
3. Please open up a new issue with the Label "Type: Bug" for this. That should not be happening and we shouldn't need to abort the software to get this to run properly. 

To add onto number two, it not possible for the program to shut down and window stay open with an exe. Windows (Microsoft) can only draws programs that are running. You can go the other way around and tell windows to stop drawing a window for a period of time (intended for use when dragging and dropping, taking screenshots etc) but you cannot force it to draw something that doesn't exist.

**Comment by aditi-nethwewala** [comment]
I will create a new issue, but I think this is a difficult one to figure out. Also, it does not happen all the time. I will test the rest.

**Comment by Monkeymerlot** [comment]
Clarification on 2: when I say the development environment is expected to "finish", it will abort the lithgraphy with a hard abort. Ie a forced shutdown.

**Comment by Monkeymerlot** [comment]
@aditi-nethwewala can you try writing a small barrier that smaller than half of the interpolation distance? I think I might have found the bug that you are talking about.

Here is the old driver's interpolation if the distance was twice the length:
![image](https://user-images.githubusercontent.com/37567672/87254091-1d857480-c44e-11ea-9ae3-24195371b76b.png)
And the new driver also suffers this fate:
![image](https://user-images.githubusercontent.com/37567672/87254206-cf24a580-c44e-11ea-98a0-a8171919ab31.png)
Thankfully there is a fix:
![image](https://user-images.githubusercontent.com/37567672/87254217-e499cf80-c44e-11ea-9f5a-a127c4bfa217.png)

Also what are the units for interpolation on the front panel? I realized I never scaled them so nothing is probably going to work...

**Comment by aditi-nethwewala** [comment]
Interpolation distance is in micrometers, so I think the above mentioned thing shouldn't be an issue. We keep our interpolation distance to be 0.001 um which is 1 nm for writing max. 50 nm wide barriers.

**Comment by Monkeymerlot** [comment]
Ok but you will still need to put them in in as meters for now in the new driver.

**Comment by aditi-nethwewala** [comment]
Ok, right now I am just testing the programs, not making it open for everyone. Also, I suggest to change it in the next version. Two reasons:

- we do not want to do unnecessary conversions, right now it is nice because we enter interpolation in the order of um and nm
- we want to keep few things consistent with before and not cause confusion, interpolation distance would be one of them

**Comment by Monkeymerlot** [comment]
Oh I totally agree, it'll definitely be fixed before the next release. I just dont want _you_ to not be able to do anything while you're testing.
