### ISSUE TITLE
Rearranging functions on AFM settings tab

### ISSUE THREAD

**Issue by aditi-nethwewala** [levylabpitt/AFM-Lithography#52]
May be it is better to have the set point and interpolation distance separate from the rest as these are the only two functions the user is supposed to change and rest should be left unchanged

![image](https://user-images.githubusercontent.com/61893772/87228080-e4c19e80-c36c-11ea-922f-eefbce09c397.png)

**Comment by Monkeymerlot** [comment]
Agreed. Thanks for the feedback!

**Comment by Monkeymerlot** [comment]
Changed it to be like this:
![image](https://user-images.githubusercontent.com/37567672/87234863-1fdec480-c3a3-11ea-8b6e-4e87e27e41cb.png)

**Comment by aditi-nethwewala** [comment]
Can you arrange it the following way please. Thank you

Move set point                   Writing setpoint
Amplifier                             Interpolation (um)

**Comment by aditi-nethwewala** [comment]
I think it messed up the comment, but basically same as you did, just swapping some positions

**Comment by Monkeymerlot** [comment]
So in terms of quadrants (I-IV):
I. Write setpoint
II. Move Setpoint
III. Amplifier
IV. Interpolation
???

**Comment by aditi-nethwewala** [comment]
![image](https://user-images.githubusercontent.com/61893772/87262594-87bb0b00-c488-11ea-9a9b-57ff97377cad.png)
 
I had something like this in mind

**Comment by aditi-nethwewala** [comment]
You can also put "(do not change)" beside Hardware setup

**Comment by Monkeymerlot** [comment]
Done and I will put a popup making sure whoever is changing the values is positive that they understand what they are doing. However, looking forwards I think that having something that should be the same every time should be in configuration instead of being a control and then in order to change it you open up a menu. 
![image](https://user-images.githubusercontent.com/37567672/87262879-8b9b5d00-c489-11ea-8556-500862dbfc95.png)

**Comment by Monkeymerlot** [comment]
Dialogue:
![image](https://user-images.githubusercontent.com/37567672/87263643-ce5e3480-c48b-11ea-83f9-12e00beb40d4.png)
and for a really special effect I added Beep.vi (its the sound that windows makes when you try to change a sound you aren't supposed to. )

**Comment by aditi-nethwewala** [comment]
Great! Thank you

**Comment by Monkeymerlot** [comment]
Is this scary but truthful enough for the Move Setpoint?
![image](https://user-images.githubusercontent.com/37567672/87264114-29445b80-c48d-11ea-8a06-e99282dc8cbe.png)

**Comment by aditi-nethwewala** [comment]
I think so, I have never seen anyone messing with the move set point in all the years I have been here

**Comment by Monkeymerlot** [comment]
Neither have I, but I was thinking that its more for 
1. other groups that might use this software 
2. someone is tired and they accidentally do the wrong set point
3. a new user does it on an accident.
