### ISSUE TITLE
Configuration + ActiveX Issues

### ISSUE THREAD

**Issue by jlevylab** [levylabpitt/AFM-Lithography#56]
Video here (2m): https://drive.google.com/file/d/1on2hc9t9XwDA0p0l4jX0_fZdNfgObFqS/view?usp=drivesdk
there are some class errors and also drag and reorder paths doesn't seem to work.

**Comment by Monkeymerlot** [comment]
Drag and drop reorder issue has been resolved in develop (issue #49). 
Class not registered: This is related to LabVIEW not finding Igor Pro on your computer. If you do have Igor pro on this computer, let me know. @aditi-nethwewala  had some issues with Igor Pro a few weeks ago, and if you do have it installed already, this might be related to the issues that she had.
I am unsure if the persistent settings were configured correctly on that release, although I do believe they were. I will look into this.

**Comment by aditi-nethwewala** [comment]
@Monkeymerlot I don't think my issue was related to the lithography program failing to find Igor Pro . The issue which I had was licensing issue. That being said, we should run the Asylum software with Igor 6.37 (which does not happen when we download the software), but I have already mentioned this to @jlevylab earlier so he might have already taken care of it

**Comment by jlevylab** [comment]
Cypher is already running 6.37

**Comment by Monkeymerlot** [comment]
## Configuration issues fix:
The exe did not have read/write access on the Cypher Computer. This is solved by running it as Administrator. This is also why there wasn't an issue on @ciozi137 or my computer.

## ActiveX Fix: 
### Suspected issue:
The Asylum software installation did not update the windows registry notifying it that there was an ActiveX API, so when LabVIEW looks for the ActiveX API it cannot be found.
### Fix: Explicitly install Igor 6.37 (from wavemetrics, not Asylum), and then open the Asylum Version of the software when you want to communicate with the instrument.
