### ISSUE TITLE
Building Issues

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/AFM-Lithography#57]
I have been trying to compile and package the develop branch of this repository and keep running into building issues. I managed to get the build to work once, but then I tried to use the installer and it said that the files were corrupted. In attempting to build again I ran into the following error: 
![image](https://user-images.githubusercontent.com/37567672/103699520-0fce2900-4f71-11eb-886c-b11d3f40d9d6.png)

**Comment by Monkeymerlot** [comment]
Tried to build again today. Got the same error as above...

**Comment by ciozi137** [comment]
@Monkeymerlot what branch and what version of labview?

**Comment by ciozi137** [comment]
Also can you build the application or installer directly from the build spec in the lv project?

**Comment by Monkeymerlot** [comment]
Develop branch, and LabVIEW 2020, VIPM 2020.0.0 (Pro Edition)

**Comment by Monkeymerlot** [comment]
@ciozi137 Ill try that right now.

**Comment by ciozi137** [comment]
Somewhat unrelated but you should update to vipm 2020.3. and lv 20 has a service pack

Pertinent question: do we need to make a package for afm litho? Or would just building an exe be good enough? Or, can we separate the two, meaning the exe application is distinct from any packages we might need.

**Comment by Monkeymerlot** [comment]
I built the application directly from LabVIEW. It seems to work fine minus the fact that I forgot to take it out of debug mode...
![image](https://user-images.githubusercontent.com/37567672/105926870-d5f0bf80-6010-11eb-90d7-336e74464b19.png)

and I think that an installer would be fine. The goal is to get this working with Cypher.

**Comment by Monkeymerlot** [comment]
OK, it's been a while since I have even looked at NIPM. Currently updating everything.

And basically I want to merge develop into main, and make a new release. Then hopefully, with all of the corrections/bug fixes it will work on Cypher and I can get back to improving the program architecture. After this I want to implement the new parser, and then start on the tooling, as these were the parts that caused the most issues in the past. But I don't want to implement these yet because I am expecting there to be some additional bugs that will inevitably crop up despite my best efforts/unit tests.

**Comment by ciozi137** [comment]
I can look at the build tomorrow. I have a slightly different solution for applications that are strictly exe/installer

**Comment by ciozi137** [comment]
@Monkeymerlot I added a file called "Build AFM Litho Installer.vi". It's basically a simplified version of the "Auto Build Script". Make you sure you have the latest "Build Support" and "MakerHub Toolbox" packages

**Comment by Monkeymerlot** [comment]
I needed to change `src` to `lvsrc`. Running it now.

**Comment by Monkeymerlot** [comment]
@ciozi137 Does this output an installer? I only can find the exe...

**Comment by ciozi137** [comment]
There should be an exe in the "builds/latest" folder. Which will be a self-extracting installer

**Comment by Monkeymerlot** [comment]
This is what is in builds/latest for me:
![image](https://user-images.githubusercontent.com/37567672/106070792-1d3f8480-60d3-11eb-98e3-307f49648337.png)

In the builds/Application folder I have the new exe though:
![image](https://user-images.githubusercontent.com/37567672/106070848-39432600-60d3-11eb-8d04-ef9f1dcf941e.png)

**Comment by ciozi137** [comment]
How about the builds/installer?

**Comment by Monkeymerlot** [comment]
It seems like all the other files updated but the installer itself. Let me check really quick if it works.
![image](https://user-images.githubusercontent.com/37567672/106071711-d6528e80-60d4-11eb-8b2f-acb7c75d3223.png)

**Comment by Monkeymerlot** [comment]
Maybe I need to put in the correct number when I build it...
![image](https://user-images.githubusercontent.com/37567672/106071794-f84c1100-60d4-11eb-9c36-524191c25678.png)

I'll try that and get back to you.

**Comment by ciozi137** [comment]
Yes windows is smart about that actually. I’m not sure why the exe
installer wasn’t made. Did you see a blank command window pop up?

**Comment by Monkeymerlot** [comment]
That worked! And yes I did both times. It still says modified in February of last year but it installed the right thing so..

**Comment by ciozi137** [comment]
What says February?

**Comment by Monkeymerlot** [comment]
The last modified date of the installer (setup.exe)

**Comment by ciozi137** [comment]
Doesn't sound right. The installer should be called something like "afm lithography-x.x.x.x.exe"

**Comment by Monkeymerlot** [comment]
Yeah mine just days setup.exe. Have you tried building it?

**Comment by Monkeymerlot** [comment]
When I built it with VIPM earlier this month it produced an installer called General AFM Lithography-8.6.0.8-install.exe

**Comment by Monkeymerlot** [comment]
Im going to try building with the version as 8.6.0.9. I did not realize that the old attempts left behind an installer that was different than the current package number I had used (8.6.0.7)

**Comment by Monkeymerlot** [comment]
Didn't change anything....

**Comment by ciozi137** [comment]
No I didn’t try it yet. I’ll try later tonight or tomorrow

**Comment by ciozi137** [comment]
Had to install vision. Now getting FTD2 errors from relay box...

**Comment by Monkeymerlot** [comment]
If you post a quick video on how you solved the bootstrapping issues, I can do a write up for the developer wiki... Just a thought.

**Comment by ciozi137** [comment]
K I'll have an update in a minute. Building now...

**Comment by Monkeymerlot** [comment]
Ok perfect.

**Comment by ciozi137** [comment]
Simple fix: I forgot to wire the source path terminal:
![image](https://user-images.githubusercontent.com/26659428/106180717-ace44200-616a-11eb-9809-5862446decd2.png)

Output:
![image](https://user-images.githubusercontent.com/26659428/106180733-b40b5000-616a-11eb-8255-dab9940f8516.png)

Regarding the "date modified" of setup.exe in builds/installer, I think that is a generic binary like "labview.exe" that ingests some other data to install the stuff.

I could not fix FTD2XX.dll on my machine. That is a different beast:
- https://forums.ni.com/t5/LabVIEW/Unexpected-change-with-64-bit-Windows-10-LabVIEW-2017-FTDI-D2XX/m-p/3797804?profile.language=en#M1071814
- https://forums.ni.com/t5/LabVIEW/DLL-call-problem/m-p/3763986?profile.language=en#M1060249
- https://forums.ni.com/t5/LabVIEW/DLL-call-problem-FTDI-DLL-works-in-LV16-but-not-in-LV17/td-p/3764008?profile.language=en

**Comment by Monkeymerlot** [comment]
Ok so I can build it, but now it is saying that the file is corrupt... (I have tried to build twice just to make sure it wasn't a fluke)
![image](https://user-images.githubusercontent.com/37567672/106183176-e66a7c80-616d-11eb-937d-50566a7e0e2e.png)

**Comment by ciozi137** [comment]
![image](https://user-images.githubusercontent.com/26659428/106183371-22054680-616e-11eb-8287-46a4787340d2.png)

**Comment by ciozi137** [comment]
try deleting your entire builds folder

**Comment by Monkeymerlot** [comment]
Didn't fix the issue. It asks if I want to install it and then the error pops up. It seems like it might be something with the zipping? 

And I think I might have found the problem:
![image](https://user-images.githubusercontent.com/37567672/106185536-f172dc00-6170-11eb-9388-b2d4fc735fe9.png)

**Comment by Monkeymerlot** [comment]
I guess pressing OK on the "File is corrupt" dialogue probably cancelled the installation...

**Comment by Monkeymerlot** [comment]
And I am reinstalling the file libraries used in the build support package. Then I'll check the project.

**Comment by Monkeymerlot** [comment]
That didn't work. I am trying to build it with the project now...

**Comment by Monkeymerlot** [comment]
Ok so the only thing that doesnt seem to work is the zipping and extraction. It builds the installer just fine from the project (even the script seems to work fine). Maybe I can just manually create a self extracting zip using 7zip?

**Comment by Monkeymerlot** [comment]
@ciozi137 I found the issue. It is looking for 7 zip in `"C:\Program Files\7-Zip"`, but my location is `"C:\Program Files (x86)\7-Zip"`

**Comment by ciozi137** [comment]
The BAT file augments %PATH% with C:\Program Files\7-Zip. Sounds like either way 7z.exe wasn't in your path. Command line on Windows isn't so good...

**Comment by Monkeymerlot** [comment]
> Command line on Windows isn't so good...
Understatement of the past 3 decades...

**Comment by Monkeymerlot** [comment]
It worked!

Changes made to write 7z.bat.vi:
![image](https://user-images.githubusercontent.com/37567672/106190650-f38c6900-6177-11eb-99e0-066df8962545.png)

**Comment by ciozi137** [comment]
Great!
If you want to take a stab at updating the "build support" package go for it. But you need to use LV2016
