### ISSUE TITLE
PID Loop Error in Igor

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/AFM-Lithography#61]
![image](https://user-images.githubusercontent.com/37567672/106193461-8aa6f000-617b-11eb-8a4c-cb200e93b5ea.png)

**Comment by Monkeymerlot** [comment]
Documentation for the function that is providing the error:
![image](https://user-images.githubusercontent.com/37567672/106194923-76fc8900-617d-11eb-9849-32bc42a6d42b.png)

This might be due to the fact that there is no controller connected to my computer.

**Comment by Monkeymerlot** [comment]
This is not related to the EXE alone, it appears in both the development environment and the exe.

**Comment by ciozi137** [comment]
@Monkeymerlot have you installed the asylum software on your computer?

**Comment by Monkeymerlot** [comment]
I have igor installed and it says MFP3D on the bottom? That might not be the software though. Tbh I've always had problems with getting the AFM software to work right and find the correct version etc.

**Comment by Monkeymerlot** [comment]
So I guess I only have Igor:
![image](https://user-images.githubusercontent.com/37567672/106206689-7e785e00-618e-11eb-9cfb-37ed2559b1fc.png)

But when I open it up I get this:
![image](https://user-images.githubusercontent.com/37567672/106206701-86380280-618e-11eb-8723-c3cb7c9c312d.png)

But it looks like normal Igor when its finished loading except it says ARC not found and MFP3DXOP v34 up23 at the bottom... (for some reason I cannot take a screenshot when Igor is loaded...)

**Comment by ciozi137** [comment]
Hmm sounds right. There used to be a way to open the asylum software that was separate from opening Igor only. I don't know if it's like that any more. Maybe you can post a screenshot when you have a chance and @aditi-nethwewala can chime in also

**Comment by Monkeymerlot** [comment]
@ciozi137 Snagit to the rescue:
![image](https://user-images.githubusercontent.com/37567672/106512664-e802b000-649f-11eb-9c47-22593497b705.png)

**Comment by ciozi137** [comment]
Idk it looks half right - the toolbar at the bottom is good, but I think there should be "AR" menus on top.

**Comment by Monkeymerlot** [comment]
@ciozi137 Yeah I have no clue how to get the actual MFP3D software at this point. Is there a link to download it from oxford? I can't seem to find it.

**Comment by ciozi137** [comment]
@Monkeymerlot This is what I have on my home PC:
![image](https://user-images.githubusercontent.com/26659428/106519211-f73a2b80-64a8-11eb-8379-6daa69359c2b.png)

Try this link: https://support.asylumresearch.com/articles/software-downloads
you may have to register

**Comment by Monkeymerlot** [comment]
I tried to install it but then nothing worked, not even igor, so I am going to remove everything and try again.

**Comment by ciozi137** [comment]
OK make sure you have the correct version of Igor. I don't know what AR wants but it is probably Igor 6 or 7

**Comment by Monkeymerlot** [comment]
OK, so uninstalling Igor made the asylum software look correct, but then I couldn't connect to it with LabVIEW. So I reinstalled the Igor software _after_ I installed the asylum software, and now I can connect to LabVIEW as well. I still can't find that function in the help browser. Ill check if this works with the overall program and report back here.

**Comment by Monkeymerlot** [comment]
Ok so I got a more detailed answer from Igor now that I think the software is correctly installed:
![image](https://user-images.githubusercontent.com/37567672/106524598-cc53d580-64b0-11eb-8339-798b286ac200.png)
So I think that we should keep an eye on this if it still comes up with the controller attached but otherwise I am satisfied with this explanation.
