### ISSUE TITLE
Application Errors 2

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#7]
![image](https://user-images.githubusercontent.com/26659428/84814391-6e38b780-afdf-11ea-9440-69ebc77c4803.png)

![image](https://user-images.githubusercontent.com/26659428/84814451-890b2c00-afdf-11ea-8de5-23b0e97eeabb.png)

@Monkeymerlot Do we need to write surfacepic.jpg in background.vi?

**Comment by ciozi137** [comment]
I think issue is missing folder. Write JPEG will create the jpeg file, but it won't create the entire path. Add changed path to C:\ProgramData and added create directory chain:

![image](https://user-images.githubusercontent.com/26659428/84907696-83662280-b081-11ea-8ac6-1af36a72414b.png)

**Comment by ciozi137** [comment]
fixed in v8.5.3.9

**Comment by Monkeymerlot** [comment]
Yes. This is over writing the background image in the inkscape file. 
```
  <image
     id="image2993"
     xlink:href="file:///C:/AFM/surfacepic.jpg"
     x="0"
     y="0"
     width="40000"
     height="40000" />
```
So our inkscape files will need to change...

**Comment by Monkeymerlot** [comment]
We should make a conversion utility for Inkscape files, or automatically change them using the program.

**Comment by ciozi137** [comment]
Is that a "real" path or just referring to somewhere inside the inkscape
file?

**Comment by Monkeymerlot** [comment]
That is a "real" path. It is a linked file path telling inkscape where to look for the image.

**Comment by Monkeymerlot** [comment]
By changing the image located at that file path, we were changing the image shown in the lithography file.

**Comment by ciozi137** [comment]
Oh..so the image isn't embedded in the inkscape file?

**Comment by Monkeymerlot** [comment]
That is correct. Its linked. See this [link](http://libregraphicsworld.org/blog/entry/inkscape-embedding-or-linking) for what it looks like under the hood.

**Comment by ciozi137** [comment]
OK I reverted to C:\afm\surfacepic.jpg but kept the create folder chain
