### ISSUE TITLE
Switch from LabVIEW 2020 to LabVIEW 2019

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/AFM-Lithography#76]
This has caused a lot of compilation errors.

**Comment by Monkeymerlot** [comment]
See:

https://github.com/levylabpitt/AFM-Lithography/issues/74#issuecomment-1144198537

for details.

**Comment by Monkeymerlot** [comment]
@ciozi137  I switched to a more appropriate issue. I just got the following during building, which up until that point seemed like it was going fine:
![image](https://user-images.githubusercontent.com/37567672/171749495-01771bd3-c8ce-4101-b54c-2d690d374f53.png)

I am going to investigate the issue and try again...

**Comment by ciozi137** [comment]
Ok. I would try to build the application and installer from the project first. And then run the vipb builder. Sometimes the labview installer needs to be initialized somehow the first time you build something.

**Comment by Monkeymerlot** [comment]
Ok trying that now!

**Comment by Monkeymerlot** [comment]
OK it worked but I'm not convinced that was actually the correct solution...

**Comment by ciozi137** [comment]
The lockin or the afm?

**Comment by Monkeymerlot** [comment]
The AFM. Lithography used to be available from the start up folder previously.

**Comment by Monkeymerlot** [comment]
I added this to the installer build spec so hopefully it will fix the issue:
![image](https://user-images.githubusercontent.com/37567672/171770919-7179bbd8-5932-4863-84a3-57ee30a8df4f.png)

**Comment by ciozi137** [comment]
@Monkeymerlot Building worked on my computer this morning (I did not disable the progress bar):
<img width="756" alt="Screen Shot 2022-06-03 at 6 35 53 AM" src="https://user-images.githubusercontent.com/26659428/171838366-f0bda0df-beb2-48a6-9273-b322891ed1c9.png">

Start menu location looks good:
<img width="306" alt="Screen Shot 2022-06-03 at 6 40 09 AM" src="https://user-images.githubusercontent.com/26659428/171839006-ddf9d557-6d30-4ae1-b02c-d31dd4f6d648.png">

**Comment by ciozi137** [comment]
@Monkeymerlot  building with Patrick builder now. With any luck in half an hour there will be magically be a new release on GitHub

**Comment by Monkeymerlot** [comment]
Is it done? I see the tag but it doesn't have an exe is why I am curious..
![image](https://user-images.githubusercontent.com/37567672/171937851-22731c3a-34c1-4724-aa16-136e7267aadc.png)

**Comment by ciozi137** [comment]
@Monkeymerlot  Everything worked up until publishing the release ("gh create release <>...". I'm not sure about the error it gave me. I had to do the release by hand: https://github.com/levylabpitt/AFM-Lithography/releases/tag/v10.0.1.1

git flow worked great:
![image](https://user-images.githubusercontent.com/26659428/171938886-e53262ba-b862-4a13-9d63-5abdeaed2fa8.png)

**Comment by Monkeymerlot** [comment]
That release looks so clean! I definitely want to go through Patrick Builder at some point. And I actually found an error (really small issue I forgot to update when I switched from variant attributes of any data type to variant attributes consisting of JSON strings) but its with the IV Curve Plugin and it wont work otherwise so I am performing another build. 

@ciozi137  Should  I just update the release with the new build files?

**Comment by ciozi137** [comment]
Let me run my builder again. I want to see if it works or get a better look at the error

**Comment by Monkeymerlot** [comment]
OK I'll let it finish and then discard changes (I am not sure to abort the build) or is it going to write to github and stuff?

**Comment by Monkeymerlot** [comment]
I uncommented the progress bar and the build failed again.

**Comment by ciozi137** [comment]
Yeah it will write to GitHub. So you can just not push

**Comment by Monkeymerlot** [comment]
Patrick Build or the Normal Build using VIPM?

**Comment by ciozi137** [comment]
I’m doing Patrick build

**Comment by ciozi137** [comment]
Now I had the same Error 5000 that you had

**Comment by ciozi137** [comment]
Vipm build worked. Gonna try again from Patrick build

**Comment by ciozi137** [comment]
Release page updated

**Comment by ciozi137** [comment]
OK awesome. I probably need to finish setting up the lockin on that
computer. ping me if you have trouble with it tomorrow. or if I didn't
finish setting everything up

**Comment by ciozi137** [comment]
@Monkeymerlot  Fix for timeout? https://github.com/levylabpitt/build-support/issues/5#issuecomment-1148717146

**Comment by ciozi137** [comment]
That looks correct

**Comment by Monkeymerlot** [comment]
@ciozi137 did you mean to comment on something else?

**Comment by ciozi137** [comment]
No I think I was responding to “ I scheduled time tomorrow to get
everything setup on the cypher and hopefully take some data.”
