### ISSUE TITLE
New Dependencies

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#89]
@Monkeymerlot i finished the New Igor-API package and updated the VIs in this repo. I did not have imaq on my home computer so I did not check yet if all of the missing files are found. One thing to note is that the "debug mode" VI is now in the Igor package. I was on the fence if it should be part of that project, or have another copy in Asylum-API etc. Moving forward I think all of these libraries should be converted to classes.

**Comment by Monkeymerlot** [comment]
@ciozi137  Sorry I didn't see this in the mix of issues that were posted at the time. I agree. Debug mode is there essentially if someone didn't have Igor on their home computer or are trying to fix an issue in the program and want to catch all commands going to igor, so I think that is the right place for it. 

Re: Classes
I agree with this too. When I first made these libraries I did not know about OOP yet, but if I had to go back I'd have made an Igor class, and then had that as a dependency of the Asylum API Class, and then the Asylum driver have the API as a dependency in turn.
