### ISSUE TITLE
timeout should be -1

### ISSUE THREAD

**Issue by mkdiet** [levylabpitt/AFM-Lithography#92]

**Comment by Monkeymerlot** [comment]
@mkdiet Please provide a detailed description of the issue for documentation purposes.

**Comment by ciozi137** [comment]
This was me. The timeout in the state machine is currently 10 ms. there are never any states queued in the timeout frame - this leads to unnecessary CPU overhead.

**Comment by Monkeymerlot** [comment]
Oh yeah that is a carry over from the older versions of the software. Since everything is event based now (mostly), I think this would be a good change.
